### ISSUE TITLE
Banner is broken on small screens

### ISSUE THREAD

**Issue by nmashton** [NCPiedmontDSA/NCPiedmontDSA.github.io#3]
We need a `max-width` or something in there, because this banner is overflowing its box pretty badly.

![overflow](https://cloud.githubusercontent.com/assets/1625749/21223917/a31b0d1a-c297-11e6-8890-8e3bfaeb4093.png)

**Comment by michael-wojcik** [comment]
@nmashton PR created: https://github.com/NCPiedmontDSA/NCPiedmontDSA.github.io/pull/4

**Comment by LuckyJimJD** [comment]
Looks good to me. Thanks!

**Comment by michael-wojcik** [comment]
Marking as fixed after merging this PR: https://github.com/NCPiedmontDSA/NCPiedmontDSA.github.io/pull/4
